
POST http://localhost:3003/api/blogs HTTP/1.1
Content-Type: application/json
Authorization:  Bearer {token}

{
    "title": "Canonical string reduction",
    "author": "Edsger W. Dijkstra",
    "url": "http://www.cs.utexas.edu/~EWD/transcriptions/EWD08xx/EWD808.html",
    "likes": 12,
    "id": "5a422b3a",
    "userId": "64d54"
}

###
POST http://localhost:3003/api/login HTTP/1.1
Content-Type: application/json

{
    "username": "root",
    "password": ""

}

###

GET http://localhost:3003/api/blogs HTTP/1.1
Content-Type: application/json

###

PUT http://localhost:3003/api/blogs/644c47a41d5dcfc8252c631f HTTP/1.1
Content-Type: application/json

{
    "title": "DWB",
    "author": "David Walsh",
    "url": "https://davidwalsh.name/",
    "likes": 138
}
