DELETE http://localhost:3003/api/blogs/64ceadd39c548a400c1ea457 HTTP/1.1
Content-Type: application/json
Authorization:  Bearer {token}




###
DELETE http://localhost:3003/api/blogs/64ceadd39c548a400c1ea457 HTTP/1.1
Content-Type: application/json
Authorization:  Bearer {token}

{
    "title": "Canonical string reduction",
    "author": "Edsger W. Dijkstra",
    "url": "http://www.cs.utexas.edu/~EWD/transcriptions/EWD08xx/EWD808.html",
    "likes": 12
    //"userId": "64cdcd08eb66fd44e5537448"
}
